### ISSUE TITLE
Wie kann ich dich kontaktieren?

### ISSUE THREAD

**Issue by Tentoxa** [JKamue/SatWatcher#1]
War mir nicht sicher ob du noch aktiv im Internet bist aber ich habe gesehen das du hier was hochgeladen hast. Können wir vielleicht nochmal über Twitter schreiben? Geht um ein Projekt von dir und ja xd.
Würde mich über ne Antwort freuen.
Ach und sorry das ich dich über diesen weg kontaktiere.

**Comment by JKamue** [comment]
Habe mal hier im repo des eigentlichen Projektes ein Ticket dafür angelegt: https://github.com/JKamue/GommeApi/issues/8
